spring.application.name=Proyecto
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/db05
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect